### ISSUE TITLE
tile governors again broken in master and 1.0.0.38

### ISSUE THREAD

**Issue by layzsmurf** [chaorace/cqui#120]
I just downloaded the latest commits (how Do I identify version on github?)

* master 
> Latest commit 2ab7c3b an hour ago
* 1.0.0.38 
> Latest commit 64040f1 2 hours ago

It was working this morning  in 1.0.0.38 - so changes that were introduced today must have broken them again.

**Comment by chaorace** [comment]
I am unable to reproduce your issue. I am skeptical that this is actually an issue with the commits pushed today, since none of the changes pushed today affected anything remotely concerning that behavior. Could you remove all other mods and start a new save, just to confirm that this has nothing to so with any potential mod conflicts? Remember that some mods don't appear in the additional settings menu, so I really do mean to remove them when I say remove, not simply deactivating in-game.

**Comment by layzsmurf** [comment]
which branch?

**Comment by chaorace** [comment]
@layzsmurf 
master, as it now has all changes introduced in the compatibility branch. I will be deleting the 1.0.0.38 branch after I'm sure your issue is resolved

**Comment by layzsmurf** [comment]
Oh dear! Clearly a user error. I kept a backup of old CQUI folders by renaming them *.bak. Civ VI does not seem to like that. After removing all those folders and downloading and installing  the new branch the problem disappears.

Sorry for this mess.
