### ISSUE TITLE
Problems with city UI and tech/civic trees.

### ISSUE THREAD

**Issue by somohexuals** [chaorace/cqui#130]
After updating CQUI my city UI isn't fully showing and my tech/civic trees wont open.
![cqui wonkyness](https://cloud.githubusercontent.com/assets/19780864/20508594/a6f664e4-b030-11e6-87fe-1b4850af7f81.png)

**Comment by chaorace** [comment]
I'm guessing this is a mod conflict. Please clean out your mods and start a new save with just CQUI enabled. Keep in mind some mods are always enabled until you remove them from the mod install directory, so please actually remove any/all other mod files instead of just deactivating them. If that doesn't work, try deleting your old CQUI install and downloading the latest nightly again.

Also, in the future this should be posted as a question on the Gitter IRC or to me on Twitter. The issues system is for specific bug reports and feature requests, as opposed to general troubleshooting.

**Comment by somohexuals** [comment]
Thanks for the info and fast reply. I'm still getting used to GitHub so I'm really sorry for putting this in the wrong section. D:

**Comment by chaorace** [comment]
@somohexuals No worries, it's just a heads up for the future. I'm gonna close this issue now, but feel free to keep using the comments here until we sort this out.

**Comment by somohexuals** [comment]
Sorry to bother you again, but it's still being wonky. D: I completely emptied my Mods folder, removed CQUI from my DLC folder, redownloaded CQUI back to the DLC folder, and enabled CQUI in the Additional Content list. I'm not sure what to do.

**Comment by somohexuals** [comment]
It seems to only act up if I try to use version 0.6 for some reason.

**Comment by ProustIdee** [comment]
Don't use version 0.6, it isn't compatible with the new patch. Version 0.7 will be released soon, in the meantime you can try running the nightly version: https://github.com/chaorace/cqui/archive/master.zip but there may be bugs.

**Comment by somohexuals** [comment]
Ohh, ok. Sorry. Thanks for the info.

**Comment by CptPeterPL** [comment]
I'm getting similiar problem -> **civics tree don't show up**. Only popup with next aviable civics. I'v tried del and redownload mod/mods, play with only CQUI , reinstall the game ... nothing helped.

**Comment by chaorace** [comment]
@CptPeterPL Are you playing on OSX/Linux?

**Comment by CptPeterPL** [comment]
Nope, Win 10. I'v notticed also that civ pop heads with score don't show in upper right corner.

/ game 1.0.0.56 (110 getting crash - i'm waiting on support help).

**Comment by chaorace** [comment]
@CptPeterPL Try downloading the OSX/Linux version. That version is built for game version 1.0.0.56, which is the latest on OSX/Linux. The other solution for you would be to update your game to latest. I suggest the latter solution since the 1.0.0.56 branch is only supported so long as OSX/Linux are still lagging behind

**Comment by CptPeterPL** [comment]
I would love to update to latest but I'm still waiting to get crash problem resolved. OSX/Linux ver is working :) thank you
