### ISSUE TITLE
GP Panel: Show number of turns remaining until great person achieved

### ISSUE THREAD

**Issue by chaorace** [chaorace/cqui#149]
This would be in the bottom of the GP panel where the meters are, one number per player per row. See #147 for details.

**Comment by emperorfool** [comment]
The number of turns remaining for each player is the most important piece of information. To keep things legible, I'd replace the X/Y progress with the number of turns remaining and expand the popup:

* Current / Needed (Turns left)
* Points per turn
* Points from each source: districts, buildings, wonders and policies
* Order of players

**Example**

(icon) Great Scientist
309 / 360 (7 Turns)

+8 per (clock) Turn
* +3 from Districts
* +2 from Buildings
* +1 from Wonders
* +2 from Policies

Order
* 3 Turns - India
* 7 Turns - America (you)
* 29 Turns - Russia
* Never - Spain

**Comment by Frozen-In-Ice** [comment]
I've been messing around in GreatPeoplePopup.lua and .xml to add the the turns remaining, and this was the best that I could do without removing anything:
![screenshot 2016-12-31 20 33 38](https://cloud.githubusercontent.com/assets/19610489/21579910/449552f0-cf99-11e6-940f-ccca23b94e96.png)
You'll notice that I had to make each Civ's entry bigger vertically, which means you might have to scroll down more. Any feedback? I can try making other versions, possibly moving the X/Y progress to the tooltip, to try to return it back to two lines.

**Comment by vttale** [comment]
Probably should open a separate issue, but this reminds me that "All individuals of this type have already been earned" doesn't actually say WHAT type.  You can infer from position and which ones are still available, and it is especially easy to tell with Great Prophets if you are anything other than a complete beginner, but it would still be better to be explicit.  Maybe even shrink the column width when the GPP is unavailable; with my 4:3 monitor I don't fit the whole GP panel on the screen and have to scroll, with a bunch of that space being wasted on at least the Great Prophet slot.

**Comment by Frozen-In-Ice** [comment]
I've made some further adjustments. I've made the popup take up the whole width of the screen on a 16:9 monitor, just as the civic tree, tech tree, and government screen already did. This let me space out the recruitment standings so that they don't overlap a bit as they currently do. I also made the standings box a bit taller, and got rid of the X/Y progress line and moved those number to the tooltip as the progress bar already provides a visual representation of those. This made the standings return to two lines per civ, so more civs can be shown on the standings before having to scroll. My monitor is showing 5 now.

Also as vttale suggested I was able to get the GP class name back in even when there's none left. In pictures:
![screenshot 2017-01-01 22 42 54](https://cloud.githubusercontent.com/assets/19610489/21584399/cf08c81e-d074-11e6-8b16-404df089fb2d.png)
![screenshot 2017-01-01 22 43 19](https://cloud.githubusercontent.com/assets/19610489/21584400/d0ac2c42-d074-11e6-892b-a019d42168ac.png)
