### ISSUE TITLE
Keybindings not working; macro labels exposed

### ISSUE THREAD

**Issue by vttale** [chaorace/cqui#174]
I am not sure whether these are related issues, but reloading a game in progress from autosave has resulted in both various custom labels being exposed (eg, LOC_TRADE_SORT_BY...) and in keybindings not working at all.  The latter is true even though the regular game options panel indicates that the bindings are still set.  I haven't noticed either of these problems when not running the mod.

**Comment by chaorace** [comment]
This is a bug with all custom LOCs due to a bug in Civ VI. There is nothing we can do as mod authors to prevent this bug at this time besides deliberately not localizing our mods. For the core CQUI files, I've done exactly this, avoiding the inclusion of any custom localization to the extent of borrowing from other files as much as possible and hardcoding strings. Other mods included in CQUI may not do this, such as the Better Trade Screen mod. There's not much I can do about this at he time, and the only components of CQUI that are affected are ones that I do not directly maintain, so I'm closing this issue
