### ISSUE TITLE
Competing completed wonder notification suppressed?

### ISSUE THREAD

**Issue by vttale** [chaorace/cqui#175]
At least twice in this game now someone has beaten me to a wonder I was in the process of constructing but I've gotten absolutely no notification about it.  I don't see a filter even present for it under Construction for Gossip -- and anyway, it isn't a Gossip I'm missing but the icon notification on the lower right.

**Comment by chaorace** [comment]
I can't visualize a situation where any of the changes I've made would interact with wonder notifications... I'll look into this more later, but I'd definitely like to be able to confirm this. Could you provide an autosave from your affected game, preferably from a little before the notification should have fired?

**Comment by vttale** [comment]
I honestly I have some doubts now that it really happened, even though at the time I was sure of it.  I think you should close it and I will reopen if I see it again.

**Comment by chaorace** [comment]
@vttale Alright, keep me posted if you're able to capture this in the wild!

**Comment by vttale** [comment]
Reopening because I have a save game where it just happened.  CQUI isn't necessarily implicated, but maybe it is related.  I've only observed it with CQUI enabled.

If you click continue from this save, the Forbidden City in Mbanza Kongo (which had one turn left, sigh) stops production but there is no notification of someone building it.

As an aside, I'm not particularly proud of this game.  First go with Kongo and I don't think I yet have quite the right feel for how to play him.  The duplicate NPC Kongo in the game is kicking my ass in culture.
[MVEMBA 105 1480 AD Forbidden.Civ6Save.zip](https://github.com/chaorace/cqui/files/671390/MVEMBA.105.1480.AD.Forbidden.Civ6Save.zip)

**Comment by chaorace** [comment]
@vttale Huge thanks for capturing this bug in the wild, will look into getting this fixed before v0.7 release

**Comment by RealAntithesis** [comment]
I've also lost a couple of wonders but no notification comes up. The first time, I was wondering what was happening with a wonder I remember starting to build quite a few turns back, but had quietly dropped off the radar and disappeared. I probably just got the new build request coming up for the city, but because I'm getting too used to the last built bug in vanilla Civ6, I probably didn't notice it was due to my wonder cancelling. Then I actually caught another wonder just deconstructing itself right in front of my eyes, with no notification. Anyhow, I'm not sure if its due to this mod since it's been awhile since I've played without mods :)

**Comment by chaorace** [comment]
I've force-loaded this save without CQUI and found that this bug happens even in vanilla. Closing this since issue since it's a bug in the base game. I've opened an issue for this over on my issue tracker for vanilla Civ UI bugs [here](https://github.com/chaorace/Civ6-UIFiles/issues/3)
