### ISSUE TITLE
Maximize Minimap Button Stretched

### ISSUE THREAD

**Issue by calcorum** [chaorace/cqui#22]
Hi - just a quick bug report. I'm playing on 1080p @ 59Hz and the maximize minimap button is stretched really wide. I've attached a screenshot for your reference. Let me know if you would like anything other info!

Thanks,
Cal
![stretched maximize button](https://cloud.githubusercontent.com/assets/9707504/19834708/50ca764c-9e41-11e6-9892-b74322a5eb72.jpg)

**Comment by chaorace** [comment]
This is a feature, not a bug. When I made the minimap larger I wanted to make expanding/collapsing the minimap an easier task without fumbling at the small UI button. The collapse button is normal in size because you can just right click the minimap when expanded to hide it. Once we get mod tools I can create a custom button instead of forcing the built-in UI elements into uncomfortable shapes
