### ISSUE TITLE
Match folder structure of all folders to \Assets\ as root for consistency

### ISSUE THREAD

**Issue by bestekov** [chaorace/cqui#222]
Enhancement/cleanup suggestion. When I tried to manually apply CQUI to my base game (to use in MP when one friend didn't want to use it), I realized that all the various mod folders have different root folders. Some are directly in \UI, some should be \Assets, some are \UI\Screens.

It would be a lot easier to write a script to generate a merged folder structure if every folder used the same folder as its root. Since at least one mod folder has \Assets as it's root, I recommend using that as the base.

Here's how it would shake out:

- \BTS\*  -- _No change, already has \Assets as the root_
- \CQUI\* -- _No change, location is arbitrary_
- \ML\* -- _No change, already has \Assets as the root_
- \PQ\* --> \PQ\UI\*  (Insert UI in the folder structure)
- \UI\* --> \CQUI\UI\* (Nest under CQUI)
- \URS\* --> \URS\UI\Screens\* (Nest two levels deep in correct folder path)

**Comment by chaorace** [comment]
I agree and think this is a good idea, so let's hash out some of the specifics here in this issue.

For one, I think it's time that some of the older integrated mods get considered for being moved into the CQUI directory. DIvine Yuri's panel is already merged in, since it's not updated anymore and considerable CQUI-exclusive modifications have been made to it in the process. I'd like to do the same for PQ, and URS, which have not been updated recently and which are due to be receiving some custom CQUI modifications in the near future.

I think it's a good idea to move the UI folder to nest inside of CQUI for consistency. That's a bit of a relic that doesn't make sense anymore, all things considered. I also think it's a good idea to move the LOC files to a Text directory inside CQUI to match the established convention elsewhere. I think the settings SQL file can remain where it is for now though

As for scripts, I think it's a good idea to have them! Any script that does modify the base game files will need to create a backup before anything else AND preferably compress it. It's probably also going to be necessary to store and detect the game version of the backed up files so that it doesn't restore incompatible files. I'm thinking of having two versions of the script: BAT for Windows and BASH for OSX. I can't support the OSX version myself, but it's something I'd like to have if I can find a volunteer.

**Comment by bestekov** [comment]
I started a CMD script (windows only here) earlier (when I ran into the directory nesting issue and did it manually). The approach I was considering was:

1. Consolidate all the directories into one temp directory
2. Write an install log/manifest of those files
3. Loop through the log and rename the target file in the Asset directory to *.*.bak
4. Copy the files over
5. Copy the install log to the base civ folder for use in later uninstalls

Then, I'd have a separate uninstall script to do the behavior in reverse.

batch scripting is pretty limited and clunky, but I'm open to suggestions if you have better ideas.

I started a script over in my "NoDLC" branch: https://github.com/bestekov/cqui/blob/NoDLC/CQUI_ApplyToBase.cmd

But I gave up and did it manually when I realized I'd have to restructure everything.

**Comment by bestekov** [comment]
The other tricky thing is that (as I noted in the gitter feed) anything requiring database updates (ML and CQUI menu itself) won't work because the db doesn't get updated. Fortunately, the rest of the mod works fine.

**Comment by bestekov** [comment]
One other thought, if you will consolidate, why have CQUI folder at all? Why not just name it "Assets"?

**Comment by chaorace** [comment]
I'd go with a PS script instead if it wasn't such a pain to get them to run by default. The other option is just throwing something together in Java, which has the advantage of being cross platform, but is going to need its own repo

**Comment by chaorace** [comment]
DB updates can probably be done by monkey patching the updates into a game sql file during the install process. As for changing the CQUI directory name to Assets, I like the folder structure as it stands. Not much rhyme or reason other than me thinking it makes more sense the way it is

**Comment by bestekov** [comment]
I tried putting them into a game SQL to no avail. But kudos to you if you
can get it to work.

And yeah a PS script would be easier but I figured a bat would be more
reliable for a non-technical consume (same with making it a .Jar) .

**Comment by GrantSP** [comment]
This may require the readme to be changed to reflect the different file structure?
