### ISSUE TITLE
No scrolling in building options

### ISSUE THREAD

**Issue by thyeestes** [chaorace/cqui#224]
It is not possible to scroll through all building possibilities if the list longer than the screen can display. Can work around by collapsing a category so that the bottom of the list is visible

**Comment by biship** [comment]
This bug is reproducible for me.
Load a game, scrollbar is there and works fine. 
Press escape to close the city view, go back into the city view and the scrollbar is gone and you can no longer scroll.

**Comment by Riskke** [comment]
Yeah, I also have this bug. I think is produced by an error in the production queue as when queued a campus, the library below appeared displaced to the right making the bar "dissapear".

**Comment by BTSeven7** [comment]
I have this bug as well.  Same as described by the other three posters.

**Comment by chaorace** [comment]
Yep, I hear you guys. Working on fixing this soon. Until then, you can sometimes fix this by expanding/collapsing the header for one of the build categories. You can also revert to nightly 2f0a5e580a2f205d601b65aa9f6374b0250f99d8 [here](https://github.com/chaorace/cqui/archive/2f0a5e580a2f205d601b65aa9f6374b0250f99d8.zip) until this issue is resolved
