### ISSUE TITLE
Please clarify the latest stable release

### ISSUE THREAD

**Issue by tbirrell** [chaorace/cqui#265]
The [README](https://github.com/chaorace/cqui/tree/v0.6-alpha#how-to-use) points me to [this release](https://github.com/chaorace/cqui/releases/), but it is 3 months old and potentially incompatible. Can you either make clear in the README that [this](https://github.com/chaorace/cqui/releases/tag/v0.6-alpha) is, in fact, the latest stable release? Or edit that line to reflect the current nature of the mod?

Thank you! I look forward to using this mod in the future.

**Comment by chaorace** [comment]
That _is_ the latest stable release. It's a bit of a sorry state of affairs, but this mod has become exponentially more time consuming to maintain and that's really slowed down the rate of new releases. Longstanding promises, bugs, and lingering stale code just need to be given some considerable elbow grease before another release-quality package can be made available (alongside the additional Q&A and documentation writing that goes along with that!). I plan to push out a new stable release when these promised things are ready and the related bugs are squashed. The mod is in a semi-featurefreeze until then.

Here's the basic roadmap to v0.7 release (which is also going to be what I consider the first beta release):
* Rounding out the Chinese, Italian, Polish, and Russian translations to being largely complete (including mod integrations), polished, and mostly bug-free (#254). This particular point has a lot to do with putting a freeze on new features
* Fulfilling longstanding promises related to making more of the existing features optional. This often requires refactoring older features entirely, which can cause bugs, which can consume even more development time (#134).
* Documentation. It's become increasingly difficult to find time for keeping the docs up to date between programming, debugging, issue tracking, and corresponding with contributors. Often times I'll need to go out of my way to track down contributors and find a way to properly attribute them. Then there's the actual editorial nightmare of adequately summing up hundreds of tweaks, shortcuts, and redesigns in a somewhat succinct and organized feature list.

So, that being said, the best thing I can offer right now is the latest nightly, as is mentioned in the linked release page. At the moment it's relatively stable and nearly all of the issue reports I am receiving these days boil down to user error instead of a mod issue (even those are becoming relatively rare @ roughly 3k+ unique visitors every 2 weeks and only a handful of support requests). Reset assured, eventually there will be a nice stable release version, which, once finalized, I'll keep on a separate branch and regularly bring bugfixes/patch updates to. It's actually where pretty much 100% of my efforts are being concentrated right now actually.

To answer your second question: the README is getting a complete rewrite in the near future as part of the planned v0.7 release

**Comment by vttale** [comment]
Thank you for writing this response.  It is solid communication when so often other developers just lapse into silence.  Your users very much appreciate the work you're doing.
