### ISSUE TITLE
German translations.

### ISSUE THREAD

**Issue by frytom** [chaorace/cqui#270]
I've done all german translations. Please integrate the translations into the nightly build. Thanks.

[DLC.zip](https://github.com/chaorace/cqui/files/729815/DLC.zip)
#254

**Comment by chaorace** [comment]
Can do, thanks for contributing!

**Comment by frytom** [comment]
Some minor tweaks, built on newest nightly.

[cqui-AddedGermanInserts.zip](https://github.com/chaorace/cqui/files/741255/cqui-AddedGermanInserts.zip)

**Comment by frytom** [comment]
In CQUI_Text_General.xml line 27
`  
    <Row Tag="LOC_CQUI_GREAT_PERSON_PROGRESS" Language="en_US">
      <Text>Progress:</Text>
    </Row>`
has the command "Row" to be replaced with "Replace" for the translations, or keep "Row"?

**Comment by chaorace** [comment]
Hmm! I hadn't even noticed that in the LOCs. I'm guessing it must work since nobody's reported any issues with it yet, but nonetheless I'd like that file to be consistent with the rest. Feel free to use whichever convention you prefer for now, I'll be doing a corrective styling pass for this in the future closer to release

**Comment by chaorace** [comment]
Resolved in 24dad270f84770fe6a211475361a0ff3ea046c24
