### ISSUE TITLE
City Tab doesn't work

### ISSUE THREAD

**Issue by Furiaa** [chaorace/cqui#281]
![civilizationvi_2017-01-30_16-02-31](https://cloud.githubusercontent.com/assets/25468214/22486895/1614bf60-e7ea-11e6-8ceb-2894b5cd49c0.png)
I can't choose production or anything.
Am I doing something wrong?

**Comment by chaorace** [comment]
Are you using Divine Yuri's Citypanel mod?

**Comment by Furiaa** [comment]
No, only this one.

**Comment by chaorace** [comment]
Alright, could you provide a copy of your save file please?

**Comment by Furiaa** [comment]
[MONTEZUMA 1 4000 BC.zip](https://github.com/chaorace/cqui/files/746477/MONTEZUMA.1.4000.BC.zip)
I checked the mod folder and I think Divine Yuri's Citypanel is included. I downloaded the latest nightly.

**Comment by chaorace** [comment]
Yes, based on your savedata it seems like Divine Yuri's Citypanel is on. You need to remove it from the mods folder or it will keep breaking CQUI, as the mod enables itself by default. There is a version of Divine Yuri's Citypanel already built into CQUI anyways, so you won't be losing anything by removing it

**Comment by chaorace** [comment]
I've loaded your save and confirmed that there's no mod conflict from loaded files, though, I was unable to replicate the issue on my setup:

![](http://i.imgur.com/5ogYm23.jpg)

This indicates to me that your install of Civ VI may be to blame. From the main menu, does the bottom left corner say 1.0.0.56? If you are fully updated, then I can only guess that perhaps your CQUI install has become corrupted somehow. This can happen if there's an issue during the download or unzipping process (or, potentially, if you tend to upgrade CQUI by overwriting the old files, which is NOT recommended, because files change names frequently and duplicate files break things). Try deleting the existing CQUI directory and downloading a fresh copy to replace it with

**Comment by Furiaa** [comment]
There was a problem with the file. I downloaded it again and it seems to work fine. Thank you for your help and sorry to waste your time. :)
