### ISSUE TITLE
Implement Production Queue

### ISSUE THREAD

**Issue by appdevtk** [chaorace/cqui#34]
Maybe the addition of a production queue:
[Reddit](https://www.reddit.com/r/civ/comments/5aqa9b/civ_6_needs_to_bring_back_the_production_queue/)
Civ 4 style, maybe first for units.

**Comment by chaorace** [comment]
There's lots of commented out logic regarding a production queue in the base game files. I think the queue was either not finished in time for release or scrapped. One of the reasons I can imagine the queue getting scrapped are districts/wonders, which require interacting with them in a very specific context when they start getting built. I think it's wise to wait and see if Firaxis finishes this feature before I try my hand at implementing it

**Comment by jacks0nX** [comment]
Could this potentially implemented by us? Create a table in a central class which holds hashes of buildable items. Use events to push items into this list and use GameInfo to get the corresponding icons and texts for the items in the queue to display. React on BuildingComplete (or something like that)  and simply request a build operation. 

Sounds fine on paper, I think. :)

**Comment by jacks0nX** [comment]
I'm actually making pretty good progress, functions to handle the queue are now (mostly) functioning and I can see first results in the GUI.

![image](https://cloud.githubusercontent.com/assets/2789832/20015767/048eb7e0-a2bd-11e6-8f37-3c9fc5eca7ef.png)

Adding works, reordering works, removing works. Next on the list are the names, icons and building the next queued up item.

**Comment by chaorace** [comment]
Well look at that! If you need help with anything just ask and I'll see what I can offer

**Comment by kblease** [comment]
Just thought I'd chime in myself. I worked on this yesterday and got it fully functioning. You can drag to reorder them, right-click to remove, double left-click to move it straight to the top. Obviously more/different input events could be added/changed. It's pretty much just the interface that needs a little attention now.

It can also handle placed buildings like wonders and districts. It will ask where you want it when adding to the queue. It won't actually place it on the plot you chose until it is in the first position. But I've also made sure to block off the tile you chose from being available when placing further districts and wonders.

I was going to put a little more work into today but thought I'd check to see if anyone else has been doing the same, and indeed someone is!

![prodqueue](https://cloud.githubusercontent.com/assets/3176153/20016592/6082a4ca-a27d-11e6-998d-fa1a40651b5e.png)

**Comment by chaorace** [comment]
@kblease That's a very nice implementation! It seems more streamlined and ready than what jacks has achieved thus far, so I'm inclined to want to use yours if you'd like to contribute it (though I wish you'd mentioned it earlier). One minor critique I have to offer is that the top of the production panel seems like a bad place to be putting this, since it's already one of the most overpopulated UI elements. Perhaps this would be better off moved to the bottom of the production panel, or even stashed in the citypanel?

**Comment by jacks0nX** [comment]
Looks great, definitely better than mine. :) Decided to use what was already there, hidden by the devs.
I'd also say that the city panel would be the best choice to place it.

Were you able to add items to the actual buildQueue of the city or how did you acheive this?

**Comment by chaorace** [comment]
@jacks0nX By the way, would you like me to add you as a contributor so you can assign yourself to issues in the future? You've certainly done enough for the project by this point to deserve it, and it could help us avoid stepping-on-toes situations like these in the future

**Comment by kblease** [comment]
Putting it at the top of the production panel was really just where I dove in to begin with. I agree, it's incredibly cramped there, especially later in the game. If the production panel items were a bit thinner it'd be better, but I don't know if that's a change folks would like. Ultimately it sounds like having it in the city panel is probably the best location.

Major apologies for not speaking up sooner. I wasn't sure if I would have the time to make any solid progress and decided to just stay silent. I think now it was probably the wrong decision.

I am tracking the queue in my own table and just passing items to the buildQueue as necessary. Doing this I am also able to serialize the data and save it to the save file so the queues are safe and sound when loading back in. It's not compressed at all, but I'm not really interested in worrying about that right now.

I will be able to work on this more later today. I have a pretty small list of things I think are important to be done before I'm comfortable with it. I will keep you informed. Thanks for the kind words! Sorry again for the toe stepping.

**Comment by chaorace** [comment]
@kblease 

I've actually got some changes for the production panel stashed away currently. Here's what those look like:

**Comment by chaorace** [comment]
@kblease Don't feel inclined to apologize, good work is good work. I owe you thanks more than anything else!

I've actually been working privately on addressing that, [here's how my experimental implementation](http://i.imgur.com/FT00iBB.png) looks so far.

By the way, how do you plan to handle wonders/buildings in the queue? I imagine you'd have to grab focus for the city while doing that. This especially concerns me because players hate to have the screen focus snatched from them, especially after waiting for the AI / other players to let them take their next turn!

**Comment by kblease** [comment]
Thanks for being understanding! I tend to stay back in the shadows too often.

Personally I am not fond of the over-sized production list, and I would much prefer your implementation.

Right now, the way I've done it, the game will enter the placement mode when you add a wonder/district to the queue. The player selects the plot, and the usual confirmation popup comes up. Once it's in the queue, it won't bother you again. When the wonder/district arrives at the top of the queue, it will immediately and automatically place it where the player selected when adding it to the queue. Hooray, no interruptions! Of course, once it is actually placed by being in the first/active position of the queue, there's no going back. But that's not really much different than the base game anyway. After all, you will still have to confirm the placement when adding it to the queue.

Additionally, I have modified the placement mode of wonders/districts to check with the production queue to make sure it does not allow you to place anything (and does not highlight it in green) on a "reserved" plot.

**Comment by chaorace** [comment]
@kblease Excellent, that's just ideal! I can't wait to see the end result 👍

**Comment by jacks0nX** [comment]
It's probably a good idea to keep your work as a seperate repository, many people probably want the production queue feature to be isolated from other mods as standalone. Looking forward to to testing it! :P

I don't really know what a contributor can do, but if it's for the assignments I'm fine with that.

**Comment by chaorace** [comment]
I think it's fine if this is a feature that comes direct to CQUI, it's really up to you though _shrug_

**Comment by chaorace** [comment]
@jacks0nX The collaborator invite has been issued! From this point forward, I knight thee Ser Jacks0nX

**Comment by jacks0nX** [comment]
@kblease, any new progress on your side? :)

**Comment by kblease** [comment]
Nearly done! Honestly, there were a lot more considerations than I realized up front (populating the selection list based on what is queued, units being replaced by techs, etc.). It might be complete already, but I'm just running through a test game now to make sure there aren't any glaring issues.

**Comment by kblease** [comment]
I had some computer troubles last night just as I was sitting down to finish it up. A capacitor on my power supply decided it didn't want to live anymore. Anyway, got my machine all fixed up and finished my first release of the production queue as a [standalone mod and repo](https://github.com/kblease/ProductionQueue).

I am of course very much interested in bringing the queue to CQUI. I quickly chucked the files together and it doesn't _quite_ work right. It's definitely usable, but it's a little finicky. I only messed about with it for a few minutes, but it seemed like the main usability issue was with the panels not staying open when adding certain items to the queue.

Additionally, there was a minor issue updating the mod and loading into an existing save not wanting to behave correctly. The information that is used from the queue throughout the code isn't fully populated by querying GetProductionInfoOfCity, so I just need to tack on a little more and that should be fixed.

I really need to be getting to bed. I'll be running off four hours of sleep tomorrow! Thanks for your patience guys, I've been trying to juggle everything and I'm pleased to finally have something to show.

**Comment by jacks0nX** [comment]
Looks really awesome, well done!
Middle mouse clicking an entry in the list moves the camera forth and back, is that just on my end?

I personally think left click should move the item to the top of the queue and immediately start producing, since it's the most prominent mouse button and the job of the production panel is pretty much "build this". Adding to the queue seems as a secondary action to me.

I might take this off your shoulders and try to merge it, you cool with that? You could focus on your own thing that way.

**Comment by benjaminjackman** [comment]
> the only reason I can think of is brutal time pressure.

I think this is the reason from what I can gather. I remember that the game was still coming together as they were doing livestreams couple months before release. Reading over the lua code I see all sorts of TODOs (e.g. this, actual pictures for each great person, which i tried to mod in, but which is pretty hopeless until .blp gets encode / decodable or the SDK comes out). The ship date was set months in advance and they probably underestimated how long it was going to take to implement some features and just ran out of time.

However they set a good foundation for UI stuff as evidenced by the fact that people are able to add in mods for these features that are pretty robust so quickly. So the future should be pretty bright as the game get's fleshed out (hopefully in patches). Anyhow just my 2 cents.

**Comment by kblease** [comment]
@jacks0nX Thanks! I would be more than happy for you to merge it yourself. Then I can just focus on fixing reported issues.

I definitely see where you're coming from with the left click argument. My feeling was that I usually want to just add something to the queue, but when I want to focus it immediately I press the big clunky button on my mouse. I did not think of it from your perspective, but you have a great point. Ultimately there is no reason the clicking actions can't be settings. If more people report the same sentiment then I'll consider changing it and/or adding some kind of setting for it. I haven't had a chance to check the new CQUI settings menu, but perhaps it could be added there after merging?

I agree with @benjaminjackman as to why it wasn't finished. They were probably in a situation where they had to scrap/postpone things in order to get what they deemed important completed. As nice as the production queue is to have, there is a good chance that some of the other things that were being worked on until the last minute were even more critical. I guess you could say the production queue doesn't really add a lot of depth to the game, as it's more a quality-of-life feature. That said, I look forward to the day they implement the queue and add some more stuff.

**Comment by kblease** [comment]
@jacks0nX And yes, the camera jerks back and forth with the middle-click, unfortunately. It seems to be baked into the game as a "center the camera here" button, and it goes right through UI elements. I made recenter the camera to your city when performing the middle-click actions to prevent your camera from zipping off to the side, but it results in the annoying little nudge. That's really the main reason I added the other input options that do the same thing, since they do not do that.

If you have a suggestion as to how to prevent the camera from doing that, I am all ears!

**Comment by chaorace** [comment]
@kblease I think I'm going to let this mod mature for a day or two before integrating it. Thanks for putting the legwork in thus far, it's already looking fantastic!

**Comment by kblease** [comment]
@chaorace That is totally fine. As long as I am given proper credit, I am happy for it to be included whenever you are ready. And since you have shown that you really emphasize giving credit to everyone, I feel in good hands.

Thanks! I think it looks good as well, but I'm biased.

**Comment by OfekA** [comment]
I think it looks amazing, great work!

**Comment by jacks0nX** [comment]
@chaorace guess waiting a few days sounds reasonable, I'm already trying to make it work, could help later.

**Comment by kblease** [comment]
@jacks0nX I don't want to step on your toes again, but I went ahead and integrated ProductionQueue into my [fork of CQUI](https://github.com/kblease/cqui). As far as I can tell it's working properly. I had to make a couple adjustments, but it largely was fine. I also made a few changes so people who update CQUI with an in-progress game shouldn't have any funky issues. If you want to go ahead and take a look, that'd be awesome. Otherwise I think it's pretty much ready to go. Sorry again if you were actively working on it.

**Comment by jacks0nX** [comment]
Aw man, was already nearly done with that. :(
But well, if adjustments were needed anyway this is the preferred solution I guess.

Gonna try it out, glad it could be merged.

**Comment by kblease** [comment]
@jacks0nX I'm so sorry! I should probably just step back and let you guys handle things, but I ended up having some free time. As usual I need to just say something. I'm just about to commit the condensed production list changes that were committed last night after I'd done the merging.

**Comment by jacks0nX** [comment]
Nah, all good. Just tested it and seems to work properly, neat! :)

**Comment by kblease** [comment]
Might as well open an issue! I'd say at [the parent repo](https://github.com/kblease/ProductionQueue).

**Comment by chaorace** [comment]
Now that all of the in-house production panel stuff for v0.7 is ready, I'm finally starting on integrating the production queue mod! Expect this soonish

**Comment by chaorace** [comment]
All done, yay! 15fa14f79bbfaec1ebed85638f5701a35bc4dd44

**Comment by kblease** [comment]
Hooray!
