### ISSUE TITLE
Resources disappear

### ISSUE THREAD

**Issue by amideus** [chaorace/cqui#342]
Hey, 
about 20 turns in my resource icons vanish from game play completely, I can hover over the tiles they were on and it shows what resource is there, but otherwise the Icons are gone from the map? 

![icons](https://cloud.githubusercontent.com/assets/26029815/23334026/9eddc19c-fb64-11e6-961e-f85ba9316eac.jpg)

**Comment by chaorace** [comment]
Which OS are you on, where did you get your CQUI download from, and what other mods (if any) are you using?

**Comment by amideus** [comment]
Windows 10, No other mods, and downloaded it from here

**Comment by chaorace** [comment]
Alright, could you provide a copy of the affected savefile please?

**Comment by amideus** [comment]
I have tried I keep getting a We don't support that file type error even when I compress it into .zip

**Comment by amideus** [comment]
http://67.227.154.173/public/       

Here I uploaded it to my FTP server

**Comment by chaorace** [comment]
Downloaded and testing now, thanks for the help 👍

**Comment by chaorace** [comment]
I've found your problem: the "Show Resource Icons" options is disabled in your save. This may have happened "suddenly" because the "R" key is mapped to toggling that particular overlay. Here's a [demonstration video for reenabling resource icons](https://drive.google.com/uc?id=0BzRHuYM0ypGobGlvUl9zdXV4UEk)
