### ISSUE TITLE
Diplomacy Deals: colored resources already in stock

### ISSUE THREAD

**Issue by ricanuck** [chaorace/cqui#373]
Hey Char,

just modified your diplomacydealview.lua file to add the code that NQUI mod uses to highlight the already possessed resources when opening the Deal window. I think this addition is very important, and closes a gap between your mod and HellBlazer's. All credit to HB.

I think you should add the code to your mod. Attached is the modified file, tested and working.

**Comment by ricanuck** [comment]
I can't upload the zip file, don't know why. Stupid github.

**Comment by chaorace** [comment]
@ricanuck Github doesn't support attachments, which hopefully explains why you can't attach anything! If you'd like to be properly credited for your work, [consider checking out this guide and submitting a pull request](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/). Otherwise, with your permission, I'll write the code-commit myself.

Anyways, I'll be closing this issue now since it's not exactly an enhancement nor an issue

**Comment by ricanuck** [comment]
Yes, go ahead and commit the code. It’s not exactly my work as I just took the code from HellBlazer’s NQUI mod. It’s still a HUGE enhancement, if you ask me. It is extremely annoying to not be able to know within the Deal window what resources you (or the other civ) already have before trading.

Hopefully you will add this code soon, or else I will have to keep editing your nightlies to add it.
