### ISSUE TITLE
Minor UI cusotmization options?

### ISSUE THREAD

**Issue by Phrozehn** [chaorace/cqui#70]
Hi,

First off, LOVE the mod!

Just a few minor things that bother me, mainly aesthetically. One problem is that unlike in your SS, citizen buttons are transparent for me. I find I need to actually focus on them now to make sure which are used and which aren't (bad eyesight on my part, so it may not bother others). Can I fix this on my end with an option I'm not seeing?

Also, is it possible to make an option in the city screen that allows me to minimize the details window on the lef tof the screen? I find it a little cluttering when I don't want to see it. Similar request with the tile buying options. I'd love to see an option in the QUI settings window to allow us to customize this. Like, for example, keep the buttons above the yield focus bar that would toggle on those parts of the city screen to allows us to turn them off, and have them on by default when we enter the city screen, but remember which ones we turn off for every time we open the screen again. For me, and perhaps others, it just becomes very cluttered. I'd love to see that option.

my Ideal would be as follows: by default the when you click a city it behaves jsut like base CIV6, and keeping the buttons about the yield bar unchanged. No extra visual clutter until you click on the citizen/tile purchase/city details/production buttons, and have the game rmember when you had toggled on since the last time you closed the city screen. I jus t like keeping my screen as empty as possible until I actually want to allocate citizens or buy a tile.

Also, I notice that whenever I click ona  citizen bubble on a tile that the production menu refreshes. is that possible to fix, or just a consequence of having the production menu open while changing citizen placement that can't be fixed?

One more minor gripe: is possible to have an option for the housing/border expansion numbers that you baked into the city tile name?

Oh, and this is my first post on Github. I hope it's in the right section >.<

**Comment by chaorace** [comment]
Hi, to answer your questions:

* Features like citizen button transparency are going to become optional soon, now that persistent settings are possible and we've built a fully capable mod menu

* The cityview will not be receiving any optional changes in the near future for the reasons described in issue #60 . This may change once we've tackled the mountain of feature requests and moved more into the polish phase. I am, however, considering a "small mode" for the cityview UI, which keeps all of the existing panels but minimizes the utilized screen space

* This is because managing citizens changes the amount of production the city is generating, which causes things like the "turns remaining" info on the production panel to become outdated. The refresh animation _is_ a bit distracting and may be something that is adjusted in the future, but rest assured that the refresh is intentional and happening for a good reason.

* Yes, I plan to be including this in the near future, as well as breaking the "Smartbanner" feature into two seperate options, one for the citizen management icon, and one for the district icons

Also, this isn't really a post best suited to the issue tracker. Issues are best when they are narrow and describe just one enhancement/bug in detail so that it's easy to handle. That's not to say that your feedback is unwelcome, just that it would be better discussed on the [CivFanatics forum](http://forums.civfanatics.com/threads/cqui-a-qui-spinoff-v0-6-out.602771/) or the [Gitter IRC](https://gitter.im/Civ6-CQUI/Feature-Requests). For these reasons, I'm now closing this issue and marking it as invalid. Feel free to create more specific tickets describing your individual requests, I don't bite!
