### ISSUE TITLE
Localized Text File

### ISSUE THREAD

**Issue by Granrey** [chaorace/cqui#99]
It have to be in "Sid Meier's Civilization VI/Base/Asset/Text/Translations/Vanilla_xx_XX.xml"
not in DLC folder..

and it have to be only 1 file.
not 2 or more..

so merge all tags to the original 'Vanilla_xx_XX.xml' file.
and try to link the tags. i'm sure it will work!

**Comment by chaorace** [comment]
Well, I'm not going to tell users to install anything directly to their base game install, so that's a no-go. The custom localization files included actually do work currently, so I know they're just fine being installed where they are and being segmented into multiple parts. The only thing stopping me from commenting out the lines necessary to turn them on is the fact that there is a bug in the game right now that breaks all custom mod localizations after reloading saves. It's very obviously broken and I'd rather wait on Firaxis fixing this than go tricking the game into loading it a different way.
